language: node_js
addons:
 postgresql: "9.6"
node_js:
  - "11"
cache:
  directories:
    - "node_modules"
  yarn: true
install:
  - yarn install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database party_time_testdb;' -U postgres
  - yarn build
  - yarn global add sequelize-cli
  - sequelize db:migrate
script:
  - yarn test
after_success:
  - yarn coverage